crates/client/src/program_client_generator.rs
When the program name contains dash `my-program` and we are trying to create a program_client instruction, the name `my-program_instruction` is not valid. So I added a fix which replace the dash with underscore `my_program_instruction` which is a valid identifier.
=> 🐛 replace dash with underscore in instruction name

.gitignore
Since VSCode seems to be the recommended IDE ignoring project files created by JetBrains IDEs might be a good idea to prevent accidental commits.
=> Ignore IntelliJ project files

CHANGELOG.md, Cargo.lock, README.md, crates/client/Cargo.toml, crates/client/src/client.rs, crates/client/src/commander.rs, crates/client/src/config.rs, crates/client/src/lib.rs, crates/client/src/templates/Trdelnik.toml.tmpl, crates/client/src/test_generator.rs, examples/escrow/Cargo.lock, examples/turnstile/Cargo.lock, examples/turnstile/Trdelnik.toml
This ***fix*** should hopefully ***fix*** the issue #68.
The waiting time for the startup of `solana-test-validator` is increased to 15 ***(\*)*** seconds (30 retries) and the `solana-test-validator` process is killed (if running) after an unsuccessful start.
***(\*)*** this value can be configured in `Trdelnik.toml` (see edits in `README.md` and in `examples/turnstile/Trdelnik.toml`
=> ✨ Make Trdelnik configurable to fix solana-test-validator's short startup timeout

README.md
Fixes this badge (see screenshot) which I managed to break in this https://github.com/Ackee-Blockchain/trdelnik/commit/2a091dcd62a99589047f5d36d160ddc5aa614d08 commit by renaming `test.yml` to `test-examples-turnstile.yml`
=> 📝 Changed broken "test" badge to "test-examples-turnstile"

crates/client/src/test_generator.rs
After trdelnik init, hfuzz_target folder is automatically added to the .gitignore file. If the folder is already there, than it will not be appended twice. If the .gitignore file does not exist, than it is skipped.
=> ✨ Automatically add hfuzz_target to .gitignore file

crates/client/src/program_client_generator.rs, crates/client/tests/test_data/expected_client_code.rs
Removed needles question mark from generated program_client code that caused annoying clippy warnings. Also removed fully qualified Pubkey types in generated instructions to improve IDE suggestions readability.
=> 🧑‍💻 Improved program_client generated code

crates/client/src/templates/trdelnik-tests/fuzz_target.rs, crates/client/src/templates/trdelnik-tests/test.rs, crates/client/src/test_generator.rs, examples/escrow/trdelnik-tests/tests/test.rs
Added support for dynamic templates where special variable can be replaced programatically. Added deploy_by_name method to the test template.
=> ✨ Support for dynamic templates.

crates/client/src/client.rs, crates/explorer/src/parse/associated_token_account.rs, crates/explorer/src/parse/token.rs, crates/explorer/src/parse/vote.rs
Removed/Update deprecated functions, removed allow deprecated macros
=> 🔥 Removed/Update deprecated functions, removed allow deprecated macros

Cargo.toml, crates/client/Cargo.toml, crates/client/src/client.rs, crates/client/src/templates/trdelnik-tests/test.rs, examples/escrow/trdelnik-tests/tests/test.rs, examples/turnstile/trdelnik-tests/tests/test.rs
Implemented Default trait for Client, which reads keypair from default path for `solana-keygen new` - no need for hardcoded keypair for Client.
=> 🧑‍💻 trait Default for Client

crates/client/src/test_generator.rs
- Fix fuzz test name collision based on the example in the Jira Task.
- Wdyt about this solution?
=> 🐛 FIX: Check fuzz test name collision by checking the name against HashSet

crates/client/Cargo.toml, crates/client/derive/fuzz_test_executor/src/lib.rs, crates/client/src/fuzzer/data_builder.rs, crates/client/src/fuzzer/error.rs, crates/client/src/fuzzer/mod.rs, crates/client/src/fuzzer/program_test_client_blocking.rs, crates/client/src/fuzzer/snapshot.rs, crates/client/src/fuzzer/snapshot_generator.rs, crates/client/src/lib.rs, crates/client/tests/test_data/expected_source_codes/expected_accounts_snapshots.rs, crates/client/tests/test_data/fuzzer_macros/fuzz_fuzz_test_executor.expanded.rs, examples/fuzz_example3/Trdelnik.toml, examples/fuzz_example3/trdelnik-tests/fuzz_tests/fuzz_0/accounts_snapshots.rs, examples/fuzz_example3/trdelnik-tests/fuzz_tests/fuzz_0/fuzz_instructions.rs
Currently, marked as draft as branch is WIP:
I would like to open a discussion to get feedback on whether the error handling is implemented correctly. Feel free to also point out some ideas or suggestions.
=> 🥅 fuzzer error handling

Fuzzing.md, README.md, crates/cli/src/command/fuzz.rs, crates/cli/src/lib.rs
Added help comment for fuzz add command, and update documentation for the new trdelnik-tests folder structure
=> 🧑‍💻 add help comment + update documentation

crates/client/derive/display_ix/src/lib.rs, crates/client/derive/fuzz_test_executor/src/lib.rs, crates/client/src/fuzzer/data_builder.rs, crates/client/src/fuzzer/fuzzer_generator.rs, crates/client/src/lib.rs, crates/client/tests/test_data/expected_source_codes/expected_fuzz_instructions.rs, crates/client/tests/test_data/fuzzer_macros/fuzz_display_ix.expanded.rs, crates/client/tests/test_data/fuzzer_macros/fuzz_fuzz_test_executor.expanded.rs, examples/fuzz_example0/trdelnik-tests/fuzz_tests/fuzz_0/fuzz_instructions.rs, examples/fuzz_example1/trdelnik-tests/fuzz_tests/fuzz_0/fuzz_instructions.rs, examples/fuzz_example2/trdelnik-tests/fuzz_tests/fuzz_0/fuzz_instructions.rs, examples/fuzz_example3/trdelnik-tests/fuzz_tests/fuzz_0/fuzz_instructions.rs
I would say currently the best possible option to debug the fuzzed instructions sequence is to use msg!() macro inside the solana program.
This PR makes it easier to examine data and accounts passed into instructions. Here are the improvements:
- It defaults to deriving the Debug trait for Accounts and Data structs generated by the Fuzzer.
- The DisplayIx macro is extended to also display struct contents.
- In relation to the above points, the DisplayIx macro is further extended to derive a "to_context_string()" function. This is used to obtain the instruction name since the std::fmt::Display implementation now includes the struct contents, meaning to_string() would also fetch the contents - this method is further used within the FuzzTestExecutor to obtain Error Context.
- (This may be …
=> Debug-mode detailed output

crates/client/derive/fuzz_test_executor/src/lib.rs, crates/client/tests/test_data/fuzzer_macros/fuzz_fuzz_test_executor.expanded.rs
Now the `check ` method will be called only after successful transaction execution.
Also, the `get_accounts` and `get_data` methods will panic in case of error to notify the developer that the custom implementations are not correct.
=> ♻️ Refactored fuzz test executor error handling

Cargo.lock, crates/cli/src/command/fuzz.rs, crates/cli/src/command/test.rs, crates/client/Cargo.toml, crates/client/src/cleaner.rs, crates/client/src/client.rs, crates/client/src/commander.rs, crates/client/src/config.rs, crates/client/src/fuzzer/fuzzer_generator.rs, crates/client/src/idl.rs, crates/client/src/lib.rs, crates/client/src/program_client_generator.rs, crates/client/src/templates/program_client/Cargo.toml.tmpl, crates/client/src/templates/trdelnik-tests/Cargo_poc.toml.tmpl, crates/client/src/test_generator.rs, crates/client/tests/test_fuzz.rs, crates/client/tests/test_program_client.rs, examples/escrow/Cargo.lock, examples/escrow/trdelnik-tests/poc_tests/Cargo.toml, examples/turnstile/Cargo.lock, examples/turnstile/trdelnik-tests/poc_tests/Cargo.toml
Currently, the user experience during the initialization process is not the best. For example, during rustc +nightly nothing is shown within the console so it looks like nothing is happening, or it is possible to call trdelnik init on an already initialized workspace. This PR contains a lot of changes that I was trying to avoid, however, there were some unnecessary functions and logic which I think I (hopefully) successfully simplified.
Init command:
- Build - after internal discussion I agree that this command is necessary, as If the project cannot be built It can result in incorrectly generated test files. However as we only support anchor-type projects, instead of calling cargo build-sbf, this is changed to anchor build (we only support anchor-type projects)
- Programs Expansion - The …
=> Improve init

Fuzzing.md, crates/client/src/fuzzer/fuzzer_generator.rs, crates/client/src/fuzzer/snapshot_generator.rs, crates/client/tests/test_data/expanded_source_codes/expanded_fuzz_example3.rs, crates/client/tests/test_data/expected_source_codes/expected_accounts_snapshots.rs, crates/client/tests/test_data/expected_source_codes/expected_fuzz_instructions.rs, crates/client/tests/test_program/fuzz_example3/Cargo.toml, crates/client/tests/test_program/fuzz_example3/src/instructions/initialize.rs, crates/client/tests/test_program/fuzz_example3/src/instructions/withdraw.rs, crates/client/tests/test_program/fuzz_example3/src/lib.rs
This PR aims to fix a problem during the fuzz test generation in case the instruction and its corresponding context have different names, such as:
```rust
pub fn withdraw_unlocked(ctx: Context<Withdraw>) -> Result<()> {
// ...
}
```
The correct context name was not taken into account and the fuzz test broke.
Now also the situation when one context struct is reused by multiple instructions is handled properly using a type alias. For example having another instruction re-using the context `Withdraw` above:
```rust
pub fn withdraw_dummy(ctx: Context<Withdraw>) -> Result<()> {
// ...
}
```
will generate a type alias and the deserialization will be reused:
```rust
pub type WithdrawDummySnapshot<'info> = WithdrawUnlockedSnapshot<'info>;
```
=> fix/Support of non-corresponding instruction and context names

crates/client/src/commander.rs, crates/client/src/test_generator.rs
As correctly mentioned within the base branch PR #132, the expansion of .program_client is unnecessary as the lib.rs file does not contain macros. This PR fixes this issue and also fixes the issue mentioned within #132 as the faulty code snippet is removed.
=> fix/remove unnecessary .program_client expansion

CHANGELOG.md, crates/client/src/fuzzer/accounts_storage.rs, crates/client/src/fuzzer/data_builder.rs, crates/client/src/fuzzer/program_test_client_blocking.rs, documentation/docs/fuzzing/howto/fuzzing-howto-p3.md, documentation/docs/fuzzing/howto/fuzzing-howto-p7.md
This PR extends the FuzzClient trait and the functionality of AccountsStorage in order to have more flexibility to create and store an arbitrary account. This removes the previous limitation that only basic accounts operations were possible.
Now, one can create and store any kind of account. For example:
- to add account that uses the `#[account(zero)]` anchor constraint (must be rent exempt, owned by our program, with empty data)
```rust
let state = fuzz_accounts
.state
.storage()
.entry(self.accounts.state)
.or_insert_with(|| {
let space = State::SIZE;
let rent_exempt_lamports = client.get_rent().unwrap().minimum_balance(space);
let keypair = Keypair::new();
let account = AccountSharedData::new_data_with_space::<[u8; 0]>(
rent_exempt_lamports,
&[],
space,
&my_program::id(),
)
.unwrap(); …
```
=> ✨ Allow direct accounts manipulation

CHANGELOG.md, Cargo.lock, crates/client/Cargo.toml, crates/client/src/cleaner.rs, crates/client/src/commander.rs, crates/client/src/fuzzer/fuzzer_generator.rs, crates/client/src/fuzzer/snapshot_generator.rs, crates/client/src/idl.rs, crates/client/src/lib.rs, crates/client/src/program_client_generator.rs, crates/client/src/test_generator.rs, crates/client/tests/test_data/expected_source_codes/expected_accounts_snapshots.rs, crates/client/tests/test_fuzz.rs, crates/client/tests/test_program_client.rs
Currently, once the `accounts_snapshots.rs` file is generated, users need to manually import the structures stored inside the Data Accounts. This PR addresses this issue by obtaining full paths (if possible) to the defined types, employing the same logic used for obtaining full paths to the Instruction input arguments for `.program_client`.
The Test generator has been updated to consolidate all extracted data into a single vector called `programs_data`, rather than using separate fields for IDL and data required for the fuzzer.
Additional minor updates include:
- Adding `use crate::PROGRAM_ID`, as it is often used within `accounts_snapshots.rs` and is available inside `test_fuzz.rs`.
- Implementing small updates to the outputs to enhance the user experience.
=> Extend use statements and Data Accounts paths for fuzz snapshots

.github/actions/setup-trident/action.yml, .github/workflows/run_fuzz_example.yml, Cargo.lock, Cargo.toml, crates/client/Cargo.toml
Remove anchor-spl from dependencies and bump Associated Token Account program dependecy down so Trident installation is not resolving solana v2.0.1
=> ⬆️ Update dependencies so Solana v2.0.1 is not required for installation

CHANGELOG.md, crates/cli/src/command.rs, crates/cli/src/command/build.rs, crates/cli/src/command/fuzz.rs, crates/cli/src/command/init.rs, crates/cli/src/lib.rs, crates/client/src/source_code_generators/fuzzer_generator.rs, crates/client/src/templates/trident-tests/test_fuzz.rs, crates/client/src/test_generator.rs, crates/client/tests/test_data/expected_source_codes/expected_fuzz_instructions.rs, crates/fuzz/src/trident_accounts_struct.rs, examples/fuzz-tests/arbitrary-custom-types-4/Cargo.lock, examples/fuzz-tests/arbitrary-limit-inputs-5/Cargo.lock, examples/fuzz-tests/arbitrary-limit-inputs-5/programs/arbitrary-limit-inputs-5/Cargo.toml, examples/fuzz-tests/hello_world/Cargo.lock, examples/fuzz-tests/incorrect-integer-arithmetic-3/Cargo.lock, examples/fuzz-tests/incorrect-ix-sequence-1/Cargo.lock, examples/fuzz-tests/unauthorized-access-2/Cargo.lock
This PR adds functionality such that it is possible to decide during the `trident init` command if the user wants to fuzz with AccountsSnapshots macro or using accounts_snapshots.rs file.
In case of `macro` the user needs to include trident-client in his program and derive AccountsSnapshots for every context manually, then he needs to include these derived implementations in the fuzz_instructions.rs.
In case of `file` it is required to include accounts_snapshots.rs implementation within the fuzz_instructions.rs file.
=> ⚡️ Add feature to initialize trident with Macro/File (for Snapshots) option based on preference

crates/client/src/test_generator.rs
A small but important change to the ``update_gitignore`` function in the ``TestGenerator`` struct.
Modified the ``writeln!`` macro call in the ``update_gitignore`` function to add the changes in a new line.
=> :bug: updating gitignore by adding a new line #186

.github/ISSUE_TEMPLATE/1-feature.yml, .github/ISSUE_TEMPLATE/2-bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, SECURITY.md
Adding templates so descriptions will be better than this one.
=> Add templates

CHANGELOG.md, crates/client/src/lib.rs, crates/client/src/source_code_generators/test_fuzz_generator.rs, crates/client/tests/expected_source_codes/expected_test_fuzz.rs, crates/fuzz/src/program_test_client_blocking.rs, examples/fuzz-tests/arbitrary-custom-types-4/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/arbitrary-limit-inputs-5/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/cpi-metaplex-7/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/hello_world/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/incorrect-integer-arithmetic-3/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/incorrect-ix-sequence-1/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/simple-cpi-6/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/unauthorized-access-2/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/unchecked-arithmetic-0/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs
This PR introduces simple feature that allows users to initialize genesis of Fuzz Testing Environment with Account from base64 string. This is particularly helpful if you want to use some account dumped from the Mainnet where you can simply dump the Account and take the dumped content into the Fuzz Test Environment
- Closes #
=> ✨ Add possibility to add account to the genesis from base64 data

crates/cli/src/command/init.rs, crates/fuzz/derive/accounts_snapshots/src/lib.rs
This PR introduces minor updates to allow derivation of AccountsSnapshots for empty Account Context. Currently, it was not possible to derive AccountsSnapshots for empty context as the unused lifetime error was triggered. This PR updates the source code generated by the AccountsSnapshots. In case no fields are present in the Account Context, the lifetime is preserved, however, the std::marker::PhantomData is used, which ensures consistency as the lifetime will be still present also for the empty implementation. 
- Closes #
=> 🔧 Allow empty AccountsSnapshots

.github/workflows/purge-latest-docs.yaml, purge_cache.sh
Github action to purge CDN cache for Trident docs (`/latest` only)
- Closes #
=> 👷 Add purge docs cache CI

CHANGELOG.md, crates/fuzz/src/fuzz_client.rs, crates/fuzz/src/program_test_client_blocking.rs
This PR adds support to the client for manipulating the Clock Sysvar, specifically by warping to a desired slot, warping to a desired epoch, and advancing time by a specified number of seconds.
- Closes #
=> ✨ Add support for Clock Sysvar manipulation

CHANGELOG.md, crates/client/src/lib.rs, crates/client/src/source_code_generators/test_fuzz_generator.rs, crates/client/tests/expected_source_codes/expected_test_fuzz.rs, crates/fuzz/src/instructions_sequence.rs, crates/fuzz/src/lib.rs, documentation/docs/features/instructions-sequences.md, examples/fuzz-tests/arbitrary-custom-types-4/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/arbitrary-limit-inputs-5/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/cpi-metaplex-7/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/hello_world/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/incorrect-integer-arithmetic-3/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/incorrect-ix-sequence-1/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/simple-cpi-6/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/unauthorized-access-2/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs, examples/fuzz-tests/unchecked-arithmetic-0/trident-tests/fuzz_tests/fuzz_0/test_fuzz.rs
Macro to use for creating pre/post and middle instruction sequences.
- Closes #
=> Macro to generate desired Ix Sequences

crates/client/src/anchor_idl.rs, crates/client/src/source_code_generators/test_fuzz_generator.rs, crates/client/tests/expected_source_codes/expected_test_fuzz.rs
=> ✨ Fix case conversion for program packages

crates/template/src/get_ix_discriminator.rs, crates/template/src/get_program_id.rs, crates/template/src/instruction_ixops.rs, crates/template/src/lib.rs
=> ✨ Convert instruction name from IDL into snake case

.gitignore, documentation/docs/installation/installation.md, documentation/docs/installation/trident-manifest.md, documentation/docs/trident-spec.json, documentation/mkdocs.yml
Adding Trident config file specification to be linked from https://github.com/schemastore/schemastore/
- Closes #
=> ✨ Add Trident config spec file

crates/client/tests/test_fuzz.rs, crates/template/src/template_getters.rs
The syntax of types.rs file is invalid when the program doesn't contain any custom account types.
FIX: Added a default example type when no custom types are present to ensure valid syntax and provide reference to users who may want to add custom types in the future.
- Closes #
=> Fix types.rs file generation

CHANGELOG.md, Cargo.lock, crates/client/Cargo.toml, crates/client/tests/fuzz_template/instructions/process_custom_types.rs, crates/client/tests/fuzz_template/instructions/process_rust_types.rs, crates/fuzz/derive/accounts/src/lib.rs, crates/fuzz/src/trident_accounts.rs, crates/template/Cargo.toml, crates/template/src/template_instruction.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/instructions/init_vesting.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/instructions/withdraw_unlocked.rs, examples/cpi/cpi-metaplex-7/trident-tests/fuzz_0/instructions/initialize.rs, examples/cpi/simple-cpi-6/trident-tests/fuzz_0/instructions/initialize_caller.rs
This PR adds the ability to specify accounts as `mut` and `signer` within instruction accounts, additionally based on the IDL these flags are automatically derived when the template is created. 
- Closes #
=> 🚀 TridentAccounts mutability and signer attributes

crates/client/src/commander/honggfuzz.rs, crates/fuzz/src/macros/fuzz_trident.rs
Debug feeds crash file to the fuzz test binary and outputs the crash with logs instead of launching the debugger.
- Closes #
=> Update honggfuzz debug

CHANGELOG.md, Cargo.lock, crates/cli/src/command/fuzz.rs, crates/cli/src/command/init.rs, crates/cli/src/lib.rs, crates/client/Cargo.toml, crates/client/src/commander/mod.rs, crates/client/src/idl_loader.rs, crates/client/src/test_generator.rs, crates/client/src/utils.rs
Users can now specify the program for which the fuzz test will be created using an optional flag --program-name.
- Closes #
=> Add option to select which program to fuzz

CHANGELOG.md, Cargo.lock, crates/client/tests/fuzz_template/instructions/initialize.rs, crates/client/tests/fuzz_template/instructions/process_custom_types.rs, crates/client/tests/fuzz_template/instructions/process_rust_types.rs, crates/fuzz/derive/accounts/src/lib.rs, crates/fuzz/src/traits/account.rs, crates/syn/Cargo.toml, crates/syn/src/codegen/trident_accounts.rs, crates/syn/src/codegen/trident_instruction.rs, crates/syn/src/parser/trident_accounts.rs, crates/syn/src/types/trident_accounts.rs, crates/template/src/template_instruction.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/Cargo.lock, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/instructions/init_vesting.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/instructions/withdraw_unlocked.rs, examples/cpi/cpi-metaplex-7/trident-tests/Cargo.lock, examples/cpi/cpi-metaplex-7/trident-tests/fuzz_0/instructions/initialize.rs, examples/cpi/simple-cpi-6/trident-tests/Cargo.lock, examples/cpi/simple-cpi-6/trident-tests/fuzz_0/instructions/initialize_callee.rs, examples/cpi/simple-cpi-6/trident-tests/fuzz_0/instructions/initialize_caller.rs, examples/hello_world/trident-tests/Cargo.lock, examples/hello_world/trident-tests/fuzz_0/instructions/initialize_fn.rs
=> 🚑️ Seeds constraint for PDAs within Accounts structure

CHANGELOG.md, crates/syn/src/codegen/trident_accounts.rs, crates/syn/src/parser/trident_accounts.rs, crates/syn/src/types/trident_accounts.rs, documentation/docs/trident-api-macro/trident-macros/trident-accounts.md, examples/hello_world/trident-tests/fuzz_0/instructions/initialize_fn.rs
This PR aims to add support for lamports, space, and owner attributes to the account attribute macro used within fuzz test account contexts.
It will simplify the process of creating empty data accounts expected to be created before the initialization.
- Closes #
=> ✨ Add support for space, lamports and owner attributes to account macro
