Ackee-Blockchain/trident

crates/client/src/client.rs, examples/turnstile/trdelnik-tests/tests/test.rs
I've added a function `get_balance` to easily fetch the current balance of an account whilst getting rid of some boilerplate code.
=> Added a function to fetch the current balance of an account

crates/client/src/client.rs, examples/turnstile/.program_client/Cargo.toml, examples/turnstile/trdelnik-tests/tests/test.rs
Reworked the program deployment function to reduce the boilerpalte code
=> ✨ Improved the program deployment procedure

CHANGELOG.md, crates/client/src/error_reporter.rs, crates/client/src/lib.rs, crates/test/src/lib.rs, crates/test/tests/expand/basic.expanded.rs, crates/test/tests/expand/with_root.expanded.rs
=> ✨ Add client error reporter

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/client/Cargo.toml, crates/test/Cargo.toml
This PR improves specified dependencies. Firstly, some of the dependencies were not used so these are removed. Secondly, important dependencies such as Solana crates or anchor crates are moved to the workspace manifest in order to have better control over the supported versions.
=> 📌 unify dependencies, and remove unused

purge_cache.sh
=> 👷 Purge more pages in docs purge CI

documentation/mkdocs.yml
=> 📝 Add canonical versions

crates/fuzz/src/error.rs
=> ✨ Add fuzzingError with custom string message

crates/config/src/afl.rs, crates/config/template/Trident.toml.tmpl, examples/common_issues/arbitrary-limit-inputs-5/Trident.toml, examples/common_issues/incorrect-ix-sequence-1/Trident.toml, examples/common_issues/unchecked-arithmetic-0/Trident.toml, examples/cpi/cpi-metaplex-7/Trident.toml, examples/cpi/simple-cpi-6/Trident.toml, examples/hello_world/Trident.toml, examples/trident-benchmark/maze0/Trident.toml
=> ✨ Fix timeout -> runtime

Cargo.lock, Cargo.toml, crates/fuzz/Cargo.toml, crates/fuzz/src/error.rs, crates/fuzz/src/fuzz_client_impl.rs
=> 🔥 Remove solana-svm dep and migrate process into trident svm

Cargo.lock, crates/client/Cargo.toml, crates/fuzz/Cargo.toml, crates/template/Cargo.toml
=> 🚀 Released related crates

CHANGELOG.md, Cargo.lock, crates/client/tests/expected_source_codes/expected_test_fuzz.rs, crates/fuzz/src/fuzz_trident.rs, crates/template/src/test_fuzz_generator.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/test_fuzz.rs, examples/cpi/cpi-metaplex-7/trident-tests/fuzz_0/test_fuzz.rs, examples/cpi/simple-cpi-6/trident-tests/fuzz_0/test_fuzz.rs, examples/hello_world/trident-tests/fuzz_0/test_fuzz.rs
=> 🔥 Remove unnecessary function in the test_fuzz.rs

CHANGELOG.md, crates/client/src/commander/afl.rs, crates/client/src/commander/honggfuzz.rs, crates/client/tests/expected_source_codes/expected_test_fuzz.rs, crates/config/src/lib.rs, crates/fuzz/derive/fuzz_test_executor/src/lib.rs, crates/fuzz/src/fuzz_client.rs, crates/fuzz/src/fuzz_client_impl.rs, crates/fuzz/src/fuzz_data.rs, crates/fuzz/src/fuzz_test_executor.rs, crates/fuzz/src/lib.rs, crates/fuzz/src/transaction_executor.rs, crates/template/src/test_fuzz_generator.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/test_fuzz.rs, examples/cpi/cpi-metaplex-7/trident-tests/fuzz_0/test_fuzz.rs, examples/cpi/simple-cpi-6/trident-tests/fuzz_0/test_fuzz.rs, examples/hello_world/trident-tests/fuzz_0/test_fuzz.rs
=> ✨ Rename config to TridentConfig as the old name was causing issues

Cargo.lock, documentation/docs/commands/commands.md, documentation/docs/writing-fuzz-test/writing-fuzz-test.md
=> 📝 Inform to change directory before fuzz start

CHANGELOG.md
=> 🚀 Update changelog

documentation/docs/faq/faq.md, documentation/docs/features/customize-ix-data.md, documentation/docs/features/features.md, documentation/docs/features/fuzz-instructions.md, documentation/docs/features/limitations.md, documentation/docs/index.md, documentation/mkdocs.yml
Add social cards, fix warnings and typos.
- Closes #
=> Add social cards

CHANGELOG.md, crates/fuzz/src/ix_ops.rs, crates/fuzz/src/transaction_executor.rs
=> post instruction

CHANGELOG.md, Cargo.lock, crates/fuzz/Cargo.toml, crates/fuzz/src/accounts_storage/mod.rs
=> 🚀 Empty storage

CHANGELOG.md, crates/fuzz/src/fuzz_client.rs, crates/fuzz/src/fuzz_client_impl.rs
=> ✨ Warp to timestamp

CHANGELOG.md, Cargo.lock, crates/client/Cargo.toml, crates/client/config.json, crates/fuzz/Cargo.toml
=> 🚀 Release 0.9.1

CHANGELOG.md, Cargo.lock, crates/fuzz/src/accounts_storage/keypair_store.rs, crates/fuzz/src/accounts_storage/pda_store.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/fuzz_instructions.rs
=> 🚨 Fix native token account balance

.github/workflows/changelog.yml, .github/workflows/fuzz.yml, .github/workflows/lint.yml
=> 📱 Ignore docs in PRs

CHANGELOG.md, crates/client/src/test_generator.rs, crates/client/tests/fuzz_template/test_fuzz.rs, crates/template/src/template.rs, crates/template/src/test_fuzz.rs
Program IDs are automatically generated with the rest of the test_fuzz.rs file. If the program ID is either missing or empty, instructions to fill it in are provided instead.
- Closes #
=> Add program id generation

CHANGELOG.md, Cargo.toml, crates/fuzz/Cargo.toml, crates/fuzz/src/accounts_storage/account_storage.rs, crates/fuzz/src/accounts_storage/mod.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/Cargo.lock, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/Cargo.toml, examples/cpi/cpi-metaplex-7/trident-tests/Cargo.lock, examples/cpi/simple-cpi-6/trident-tests/Cargo.lock
=> ✨ Add features for optional crates

crates/fuzz/src/trident_accounts.rs, crates/fuzz/src/trident_pubkey.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/instructions/init_vesting.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/transactions/withdraw_unlocked.rs
=> ✨ Hide some TridentAccount methods and add basic TridentPubkey methods

crates/syn/src/codegen/trident_transaction.rs
=> ✨ Group together instruction calls within transaction macro

crates/client/tests/fuzz_template/instructions/initialize.rs, crates/client/tests/fuzz_template/instructions/process_custom_types.rs, crates/client/tests/fuzz_template/instructions/process_rust_types.rs, crates/fuzz/derive/accounts/src/lib.rs, crates/syn/src/codegen/trident_accounts.rs, crates/syn/src/parser/trident_accounts.rs, crates/syn/src/types/trident_accounts.rs, crates/template/src/template_instruction.rs
=> ✨ Make storage attribute available, so in case storage type changes,it can be updated for macros

Cargo.lock, crates/client/tests/fuzz_template/test_fuzz.rs, crates/fuzz/Cargo.toml, crates/fuzz/src/fuzz_client_impl.rs, crates/template/src/test_fuzz.rs, examples/hello_world/trident-tests/Cargo.lock, examples/hello_world/trident-tests/fuzz_0/fuzz_transactions.rs, examples/hello_world/trident-tests/fuzz_0/instructions/initialize_fn.rs, examples/hello_world/trident-tests/fuzz_0/test_fuzz.rs
=> ✨ Allow deploy of program in start function

crates/client/src/commander/honggfuzz.rs, crates/client/tests/fuzz_template/test_fuzz.rs, crates/fuzz/src/traits/transaction.rs, crates/fuzz/src/traits/transaction_selector.rs, crates/syn/src/codegen/trident_flow_executor.rs, crates/syn/src/codegen/trident_fuzz_test_executor.rs, crates/syn/src/codegen/trident_transaction_selector.rs, crates/template/src/test_fuzz.rs, examples/hello_world/trident-tests/fuzz_0/test_fuzz.rs
=> 🔥 Remove unnecessary config arguments

crates/fuzz/src/traits/transaction_setters.rs, crates/syn/src/codegen/trident_transaction.rs, crates/syn/src/codegen/trident_transaction_selector.rs
=> ✅ Correctly set transaction and correctly obtain transaction data

documentation/docs/basics/commands.md
Add option descriptions of fuzz add and init commands to the docs.
- Closes #
=> Add options

CHANGELOG.md, crates/syn/src/codegen/trident_flow_executor.rs, crates/syn/src/parser/trident_flow_executor.rs, crates/syn/src/types/trident_flow_executor.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/fuzz_transactions.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/instructions/initialize.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/instructions/move_east.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/instructions/move_north.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/instructions/move_south.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/instructions/move_west.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/test_fuzz.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/transactions/initialize.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/transactions/move_east.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/transactions/move_north.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/transactions/move_south.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/transactions/move_west.rs, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/types.rs
=> 🚀 Add support for random tail attribute

CHANGELOG.md, crates/fuzz/src/traits/transaction_selector.rs, crates/syn/src/codegen/trident_transaction_selector.rs, examples/trident-benchmark/maze_2/trident-tests/Cargo.lock, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/fuzz_transactions.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/instructions/initialize.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/instructions/move_east.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/instructions/move_north.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/instructions/move_south.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/instructions/move_west.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/test_fuzz.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/transactions/initialize.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/transactions/move_east.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/transactions/move_north.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/transactions/move_south.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/transactions/move_west.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/types.rs
=> ✨ Transaction Selector allows random selection and execution

crates/client/tests/fuzz_template/test_fuzz.rs, crates/template/src/test_fuzz.rs
=> 🔥 Add comment to template to help specify flows

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/client/Cargo.toml, crates/client/config.json, crates/client/src/lib.rs, crates/client/src/test_generator.rs, crates/client/src/test_generator_manifest.rs, crates/client/src/versions_config.rs, crates/config/Cargo.toml, crates/fuzz/Cargo.toml, crates/fuzz/derive/accounts/Cargo.toml, crates/fuzz/derive/flow_executor/Cargo.toml, crates/fuzz/derive/instruction/Cargo.toml, crates/fuzz/derive/remaining_accounts/Cargo.toml, crates/fuzz/derive/transaction/Cargo.toml, crates/fuzz/derive/transaction_selector/Cargo.toml, crates/syn/Cargo.toml, crates/template/Cargo.toml, examples/hello_world/trident-tests/Cargo.lock
=> 📌 Group crates metadata together

crates/fuzz/src/accounts_storage/account_storage.rs
=> 🚑️ Accounts are overriden in client if they already exists

examples/idl-test/Anchor.toml, examples/idl-test/programs/additional-program/Cargo.toml, examples/idl-test/programs/idl-test/Cargo.toml
=> 🐛 Update anchor version of test example to 0.31.0

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/client/Cargo.toml, crates/fuzz/Cargo.toml, crates/fuzz/derive/accounts/Cargo.toml, crates/fuzz/derive/flow_executor/Cargo.toml, crates/fuzz/derive/instruction/Cargo.toml, crates/fuzz/derive/remaining_accounts/Cargo.toml, crates/fuzz/derive/transaction/Cargo.toml, crates/fuzz/derive/transaction_selector/Cargo.toml, documentation/docs/basics/installation.md
=> Release updates

Cargo.lock, crates/client/tests/fuzz_template/test_fuzz.rs, crates/fuzz/Cargo.toml, crates/fuzz/src/fuzz_client_impl.rs, crates/fuzz/src/lib.rs, crates/fuzz/src/traits/fuzz_client.rs, crates/template/src/test_fuzz.rs, examples/common_issues/arbitrary-limit-inputs-5/trident-tests/fuzz_0/test_fuzz.rs, examples/cpi/cpi-metaplex-7/trident-tests/fuzz_0/test_fuzz.rs, examples/cpi/simple-cpi-6/trident-tests/fuzz_0/test_fuzz.rs, examples/hello_world/trident-tests/fuzz_0/test_fuzz.rs, examples/trident-benchmark/maze_2/trident-tests/fuzz_0/test_fuzz.rs, rust-toolchain.toml
=> ✨ Slighlty update FuzzClient api based on the TridentSVM updates

documentation/docs/basics/installation.md
Add description on how to setup trident for macOS
- Closes #
=> Add macOS setup instructions

.github/workflows/fuzz.yml, .github/workflows/lint.yml
=> 🚀 Update runners

crates/client/src/lib.rs
This PR remove commented out parts of code, align comments style and introduce a few cosmetic changes.
freestyler :)
- Closes #
=> client: fix typos / remove obsolete import and mod

.github/workflows/fuzz.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, crates/client/src/commander/afl.rs, crates/fuzz/Cargo.toml, crates/fuzz/src/fuzz_client_impl.rs, crates/fuzz/src/lib.rs, crates/fuzz/src/traits/fuzz_client.rs, crates/fuzz/src/traits/transaction.rs, crates/syn/src/codegen/trident_flow_executor.rs
=> Remove afl metrics

CHANGELOG.md, Cargo.lock, crates/fuzz/Cargo.toml, crates/fuzz/src/fuzz_client_impl.rs, crates/fuzz/src/lib.rs, crates/fuzz/src/traits/fuzz_client.rs, examples/trident-benchmark/maze_0/trident-tests/Cargo.lock, examples/trident-benchmark/maze_0/trident-tests/Cargo.toml, examples/trident-benchmark/maze_0/trident-tests/Trident.toml, examples/trident-benchmark/maze_0/trident-tests/fuzz_0/test_fuzz.rs
=> 🔥 Add features for syscalls

crates/fuzz/src/accounts_storage/account_storage.rs, crates/fuzz/src/accounts_storage/token_account.rs
=> ⚡️ Evaluate if token account corresponds to WSOL automatically

Cargo.lock, Cargo.toml, Makefile, crates/cli/Cargo.toml, crates/client/Cargo.toml, crates/fuzz/Cargo.toml, crates/fuzz/derive/accounts/Cargo.toml, crates/fuzz/derive/flow_executor/Cargo.toml, crates/fuzz/derive/fuzz_test_methods/Cargo.toml, crates/fuzz/derive/instruction/Cargo.toml, crates/fuzz/derive/remaining_accounts/Cargo.toml, crates/fuzz/derive/transaction/Cargo.toml, examples/cpi/trident-tests/Cargo.lock, examples/hello_world/trident-tests/Cargo.lock, examples/metaplex/trident-tests/Cargo.lock, examples/trident-benchmark/maze_0/trident-tests/Cargo.lock, examples/trident-benchmark/maze_1/trident-tests/Cargo.lock, examples/trident-benchmark/maze_2/trident-tests/Cargo.lock, examples/trident-benchmark/maze_3/trident-tests/Cargo.lock, examples/trident-benchmark/maze_4/trident-tests/Cargo.lock
=> 🔥 Increase version to rc and update makefile

Cargo.lock, crates/client/src/commander/fuzz.rs, crates/fuzz/Cargo.toml, crates/fuzz/src/fuzz_client_impl.rs
=> 🔥 Move logs file into artifacts folder

crates/fuzz/src/fuzz_client_impl.rs, crates/fuzz/src/traits/fuzz_client.rs, crates/fuzz/src/trident.rs
=> 🔥 Remove unnecessary method from fuzz client

crates/cli/src/lib.rs
=> 🔥 Add --version

documentation/docs/trident-manifest/index.md
Update coverage trident manifest docs.
- Closes #
=> Update coverage docs

crates/cli/src/command/fuzz.rs, crates/client/src/commander/fuzz.rs, crates/client/src/commander/mod.rs, crates/fuzz/src/trident.rs, crates/metrics/src/lib.rs, crates/syn/src/codegen/trident_flow_executor.rs
=> 🚑️ Add exit code functionality

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/command/compare_regression.rs, crates/cli/src/command/mod.rs, crates/cli/src/lib.rs, crates/metrics/src/lib.rs, crates/metrics/src/regression/compare.rs, crates/metrics/src/regression/mod.rs
=> 🔥 Add simple logic two compare two regression files

Cargo.lock, Cargo.toml
=> 🔥 Update to rc.4

CHANGELOG.md, documentation/docs/basics/faq.md, documentation/docs/start-fuzzing/writting-fuzz-test/index.md, documentation/docs/start-fuzzing/writting-fuzz-test/remaining-accounts.md, documentation/docs/trident-manifest/index.md
=> Correct some typos

documentation/docs/index.md, documentation/docs/trident-advanced/dashboard/index.md, documentation/docs/trident-advanced/index.md, documentation/docs/trident-advanced/regression/index.md, documentation/docs/trident-api-macro/trident-fuzz-client/fuzz-client-trait.md, documentation/docs/trident-api-macro/trident/trident.md, documentation/docs/trident-manifest/index.md, documentation/mkdocs.yml, examples/hello_world/trident-tests/fuzz_0/test_fuzz.rs
=> 🔥 Update docs

documentation/mkdocs.yml
=> 🔥 Update social cards
